<style>
   @media (max-width: 850px)
   {
   .contactus_rightdiv
   {
   width:100%!important;
   margin-bottom: 30px;
   }
   }
   #competition_form
   {
   width: 58%!important;
   border-right: 3px solid black;
   padding-right: 60px;
   }
   .contactus_rightdiv
   {
   float: left;
   width: 35%;
   margin-top: 60px;
   float: left;
   width: 35%;
   margin-top: 0px;
   padding-left: 13px;
   height: 100%;
   }.contactus_rightdiv a, .contactus_rightdiv b {
   font-weight: bold;
   font-family: "Gotham-Medium",sans-serif;
   color: #000000;
   }
</style>
<?php $storesInfo = $this->getStoresInfo(); ?>
<div class="contact_right contact_main_div fullscreenmobile">
   <form action="<?php echo Mage::getUrl('front_competition/index/save') ?>" class="contact-form
      fullscreenmobile"  role="form" id="competition_form" method="post" style="margin-bottom: 25px;">
      <div class="makeup_academy contact_us_header" >
         <h2>CONTACT US</h2>
      </div>
      <div class="form-group name">
         <input name="first_name" id="first_name" title="First Name" value="" placeholder="FIRST NAME *" class="input-text required-entry" type="text" maxlength="30"/>
      </div>
      <div class="form-group name">
         <input name="last_name" id="last_name" title="Last Name" value="" placeholder="LAST NAME *" class="input-text required-entry" type="text" maxlength="30"/>
      </div>
      <div class="form-group name">
         <input name="telephone_number" id="telephone_number" title="Phone/Mobile" value="" placeholder="PHONE/MOBILE" class="input-text" type="text" maxlength="15"/>
      </div>
      <div class="form-group name">
         <input name="email" id="email" title="Email" value="" placeholder="EMAIL *" class="input-text required-entry validate-email" type="text" maxlength="50"/>
      </div>
      <div class="form-group name referred_by">
         <div>Store Name</div>
         <select name="store_name" id="store_name" title="Store Name" class="input-box referbydropdown" type="dropdown" >
            <?php foreach($storesInfo as $row): ?>
				<option value="<?php echo $row['store_id'] ?>"><?php echo $row['store_name'] ?></option>
			<?php endforeach; ?>
         </select>
      </div>
      <div class="form-group name">
         <input name="postcode" id="postcode" title="Post Code" value="" placeholder="POSTCODE *" class="input-text required-entry" type="text" maxlength="15"/>
      </div>
	  <div class="form-group name">
         <input name="receipt_number" id="receipt_number" title="Post Code" value="" placeholder="Receipt Number *" class="input-text required-entry" type="text" maxlength="7"/>
      </div>
	  <div class="form-group name">
	  <div> *Complete the phrase below to submit your entry: </div>
      New York City is also known as THE BIG <input name="phrase_answer" id="phrase_answer" title="Post Code" value="" placeholder="Answer *" class="input-text required-entry" type="text" maxlength="10"/>
      </div>
	  
      <p class="required" style=" width:400px;"><font style="color:#ff0000;">*</font><?php echo Mage::helper('contacts')->__(' Required Fields') ?></p>
	  <button type="submit" name="form_submit" class="btn btn-default"  title="Submit">SUBMIT <b></b></button>
   </form>
</div>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('competition_form', true);
//]]>
</script>